// <auto-generated />
using System;
using CoursesHelperWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursesHelperWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603005033_AddInstructorAvailability")]
    partial class AddInstructorAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A certification in Information Technology.",
                            Name = "IT Cert"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A certification in programming.",
                            Name = "Programming Cert"
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.CertificationCourse", b =>
                {
                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("CertificationId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CertificationCourses");

                    b.HasData(
                        new
                        {
                            CertificationId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            CertificationId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            CertificationId = 1,
                            CourseId = 5
                        },
                        new
                        {
                            CertificationId = 1,
                            CourseId = 6
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Computer lab 19.101",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Computer lab 19.102",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Computer lab 19.103",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Engineering room 2.1",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.ClassroomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ClassroomsTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Description = "A room with 20+ computers and a smart board.",
                            Name = "Computer lab"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            Description = "A room wtih engineering equipment for 20+ students.",
                            Name = "Engineering room"
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfSessions")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Introduction to Information Technology (IT).",
                            Name = "IT 1",
                            NumberOfSessions = 10,
                            Price = 100m,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Introduction to Programming.",
                            Name = "Programming 1",
                            NumberOfSessions = 10,
                            Price = 100m,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Introduction to Business.",
                            Name = "Business 1",
                            NumberOfSessions = 12,
                            Price = 120m,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Introduction to Mechanical Engineering.",
                            Name = "Mechanical Engineering 1",
                            NumberOfSessions = 15,
                            Price = 150m,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Continuation to Information Technology (IT).",
                            Name = "IT 2",
                            NumberOfSessions = 10,
                            Price = 100m,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Continuation to Information Technology (IT).",
                            Name = "IT 3",
                            NumberOfSessions = 10,
                            Price = 100m,
                            SubjectId = 1
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.CoursePrerequisite", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "PrerequisiteId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("CoursePrerequisites");

                    b.HasData(
                        new
                        {
                            CourseId = 5,
                            PrerequisiteId = 1
                        },
                        new
                        {
                            CourseId = 6,
                            PrerequisiteId = 1
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndingTime")
                        .HasColumnType("Time");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("StartingTime")
                        .HasColumnType("Time");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            CourseId = 5,
                            DayOfWeek = 1,
                            EndingTime = new TimeSpan(0, 16, 0, 0, 0),
                            InstructorId = "instructor-user",
                            MaxSeats = 20,
                            StartingDate = new DateOnly(2026, 1, 1),
                            StartingTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 1,
                            CourseId = 5,
                            DayOfWeek = 1,
                            EndingTime = new TimeSpan(0, 16, 0, 0, 0),
                            InstructorId = "instructor-user",
                            MaxSeats = 20,
                            StartingDate = new DateOnly(2026, 1, 1),
                            StartingTime = new TimeSpan(0, 14, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.InstructorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndingTime")
                        .HasColumnType("Time");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("StartingTime")
                        .HasColumnType("Time");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId", "DayOfWeek", "StartingTime", "EndingTime");

                    b.ToTable("InstructorAvailabilities");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.InstructorQualification", b =>
                {
                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("instructorQualifications");

                    b.HasData(
                        new
                        {
                            InstructorId = "instructor-user",
                            CourseId = 5
                        },
                        new
                        {
                            InstructorId = "instructor-user",
                            CourseId = 6
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ReadAtUtc", "CreatedAtUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Information Technology: A subject focusing on hardware configuration and repair.",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Programming: A subject focusing on software development.",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Business: A subject focusing on managing companies and finances.",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mechanical Engineering: A subject focusing on moving hardware systems",
                            Name = "Mechanical Engineering"
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TakenTogether", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TakenTogethers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Two IT courses that must be taken together after completing the introduction.",
                            Name = "IT Program"
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TakenTogetherCourse", b =>
                {
                    b.Property<int>("TakenTogetherId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("TakenTogetherId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("TakenTogetherCourses");

                    b.HasData(
                        new
                        {
                            TakenTogetherId = 1,
                            CourseId = 5
                        },
                        new
                        {
                            TakenTogetherId = 1,
                            CourseId = 6
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TraineeCertification", b =>
                {
                    b.Property<string>("TraineeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.HasKey("TraineeId", "CertificationId");

                    b.HasIndex("CertificationId");

                    b.ToTable("TraineeCertifications");

                    b.HasData(
                        new
                        {
                            TraineeId = "trainee-user2",
                            CertificationId = 2
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TraineeQualification", b =>
                {
                    b.Property<string>("TraineeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("TraineeId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("TraineeQualifications");

                    b.HasData(
                        new
                        {
                            TraineeId = "trainee-user",
                            CourseId = 1
                        },
                        new
                        {
                            TraineeId = "trainee-user2",
                            CourseId = 2
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TraineeSession", b =>
                {
                    b.Property<string>("TraineeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TraineeId", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("TraineeSessions");

                    b.HasData(
                        new
                        {
                            TraineeId = "trainee-user",
                            SessionId = 1,
                            AmountPaid = 100m,
                            Status = 1
                        },
                        new
                        {
                            TraineeId = "trainee-user",
                            SessionId = 2,
                            AmountPaid = 100m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.UserInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("UserInfos");

                    b.HasData(
                        new
                        {
                            UserId = "admin-user",
                            DateOfBirth = new DateOnly(1980, 1, 1),
                            FirstName = "Example",
                            LastName = "Admin"
                        },
                        new
                        {
                            UserId = "coordinator-user",
                            DateOfBirth = new DateOnly(1985, 5, 15),
                            FirstName = "Example",
                            LastName = "Coordinator"
                        },
                        new
                        {
                            UserId = "instructor-user",
                            DateOfBirth = new DateOnly(1975, 10, 20),
                            FirstName = "Example",
                            LastName = "Instructor"
                        },
                        new
                        {
                            UserId = "trainee-user",
                            DateOfBirth = new DateOnly(2000, 12, 5),
                            FirstName = "Example",
                            LastName = "Trainee"
                        },
                        new
                        {
                            UserId = "trainee-user2",
                            DateOfBirth = new DateOnly(2000, 12, 5),
                            FirstName = "Example",
                            LastName = "Trainee2"
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.Identity.ExtraEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Email")
                        .IsUnique();

                    b.ToTable("ExtraEmail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "stu1extra@uni.edu",
                            UserId = "trainee-user"
                        },
                        new
                        {
                            Id = 2,
                            Email = "stu2extra@uni.edu",
                            UserId = "trainee-user2"
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.Identity.ExtraPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Phone")
                        .IsUnique();

                    b.ToTable("ExtraPhone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Phone = "9310134141242141",
                            UserId = "trainee-user"
                        },
                        new
                        {
                            Id = 2,
                            Phone = "901204124014021",
                            UserId = "trainee-user2"
                        });
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ADMIN_STAMP",
                            Email = "admin@uni.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@UNI.EDU",
                            NormalizedUserName = "ADMIN@UNI.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEFHS0Dcj5cV5gNNRjaUV+EZ2VKgFC6dRyt21ae+SVV+PVRBOo7GF7uI5wtH7IwltIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP_ADMIN",
                            TwoFactorEnabled = false,
                            UserName = "admin@uni.edu",
                            UserType = 4
                        },
                        new
                        {
                            Id = "coordinator-user",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "COORDINATOR_STAMP",
                            Email = "coord@uni.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "COORD@UNI.EDU",
                            NormalizedUserName = "COORD@UNI.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEFHS0Dcj5cV5gNNRjaUV+EZ2VKgFC6dRyt21ae+SVV+PVRBOo7GF7uI5wtH7IwltIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP_COORD",
                            TwoFactorEnabled = false,
                            UserName = "coord@uni.edu",
                            UserType = 3
                        },
                        new
                        {
                            Id = "instructor-user",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "INSTRUCTOR_STAMP",
                            Email = "teacher@uni.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "TEACHER@UNI.EDU",
                            NormalizedUserName = "TEACHER@UNI.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEFHS0Dcj5cV5gNNRjaUV+EZ2VKgFC6dRyt21ae+SVV+PVRBOo7GF7uI5wtH7IwltIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP_INST",
                            TwoFactorEnabled = false,
                            UserName = "teacher@uni.edu",
                            UserType = 2
                        },
                        new
                        {
                            Id = "trainee-user",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "TRAINEE_STAMP",
                            Email = "student@uni.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "STUDENT@UNI.EDU",
                            NormalizedUserName = "STUDENT@UNI.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEFHS0Dcj5cV5gNNRjaUV+EZ2VKgFC6dRyt21ae+SVV+PVRBOo7GF7uI5wtH7IwltIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP_TRAINEE",
                            TwoFactorEnabled = false,
                            UserName = "student@uni.edu",
                            UserType = 1
                        },
                        new
                        {
                            Id = "trainee-user2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "TRAINEE_STAMP2",
                            Email = "student2@uni.edu",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "STUDENT2@UNI.EDU",
                            NormalizedUserName = "STUDENT2@UNI.EDU",
                            PasswordHash = "AQAAAAIAAYagAAAAEFHS0Dcj5cV5gNNRjaUV+EZ2VKgFC6dRyt21ae+SVV+PVRBOo7GF7uI5wtH7IwltIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STAMP_TRAINEE2",
                            TwoFactorEnabled = false,
                            UserName = "student2@uni.edu",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "trainee-role",
                            Name = "Trainee",
                            NormalizedName = "TRAINEE"
                        },
                        new
                        {
                            Id = "instructor-role",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "coordinator-role",
                            Name = "Coordinator",
                            NormalizedName = "COORDINATOR"
                        },
                        new
                        {
                            Id = "admin-role",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user",
                            RoleId = "admin-role"
                        },
                        new
                        {
                            UserId = "coordinator-user",
                            RoleId = "coordinator-role"
                        },
                        new
                        {
                            UserId = "instructor-user",
                            RoleId = "instructor-role"
                        },
                        new
                        {
                            UserId = "trainee-user",
                            RoleId = "trainee-role"
                        },
                        new
                        {
                            UserId = "trainee-user2",
                            RoleId = "trainee-role"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.CertificationCourse", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Certification", "Certification")
                        .WithMany("CertificationCourses")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.App.Course", "Course")
                        .WithMany("CertificationCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Classroom", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.ClassroomType", "ClassroomType")
                        .WithMany("Classrooms")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassroomType");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Course", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.CoursePrerequisite", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Course", "Course")
                        .WithMany("CoursePrerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.App.Course", "Prerequisite")
                        .WithMany("IsPrerequisiteFor")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.CourseSession", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Classroom", "Classroom")
                        .WithMany("CourseSessions")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.App.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.InstructorAvailability", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "Instructor")
                        .WithMany("InstructorAvailabilities")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.InstructorQualification", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Course", "Course")
                        .WithMany("InstructorQualifications")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "Instructor")
                        .WithMany("InstructorQualifications")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Notification", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TakenTogetherCourse", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Course", "Course")
                        .WithMany("TakenTogetherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.App.TakenTogether", "TakenTogether")
                        .WithMany("TakenTogetherCourses")
                        .HasForeignKey("TakenTogetherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("TakenTogether");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TraineeCertification", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Certification", "Certification")
                        .WithMany("TraineeCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "Trainee")
                        .WithMany("TraineeCertifications")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TraineeQualification", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.Course", "Course")
                        .WithMany("TraineeQualifications")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "Trainee")
                        .WithMany("TraineeQualifications")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TraineeSession", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.App.CourseSession", "CourseSession")
                        .WithMany("TraineeSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "Trainee")
                        .WithMany("TraineeSessions")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.UserInfo", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("CoursesHelperWebAPI.Models.App.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.Identity.ExtraEmail", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "User")
                        .WithMany("ExtraEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.Identity.ExtraPhone", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", "User")
                        .WithMany("ExtraPhones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CoursesHelperWebAPI.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Certification", b =>
                {
                    b.Navigation("CertificationCourses");

                    b.Navigation("TraineeCertifications");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Classroom", b =>
                {
                    b.Navigation("CourseSessions");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.ClassroomType", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Course", b =>
                {
                    b.Navigation("CertificationCourses");

                    b.Navigation("CoursePrerequisites");

                    b.Navigation("CourseSessions");

                    b.Navigation("InstructorQualifications");

                    b.Navigation("IsPrerequisiteFor");

                    b.Navigation("TakenTogetherCourses");

                    b.Navigation("TraineeQualifications");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.CourseSession", b =>
                {
                    b.Navigation("TraineeSessions");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.Subject", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.App.TakenTogether", b =>
                {
                    b.Navigation("TakenTogetherCourses");
                });

            modelBuilder.Entity("CoursesHelperWebAPI.Models.Identity.User", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("ExtraEmails");

                    b.Navigation("ExtraPhones");

                    b.Navigation("InstructorAvailabilities");

                    b.Navigation("InstructorQualifications");

                    b.Navigation("Notifications");

                    b.Navigation("TraineeCertifications");

                    b.Navigation("TraineeQualifications");

                    b.Navigation("TraineeSessions");

                    b.Navigation("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
